name: Continuous Deploy

on:
  push:
    branches: ["main", "dev/*"]
  pull_request:
    branches: ["main", "dev/*"]

jobs:

  build-test:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ./industrial-holding-ui/

    strategy:
      matrix:
        node-version: [18.x]

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: "npm"
          cache-dependency-path: "./industrial-holding-ui/package-lock.json"
      - run: npm ci
      - run: npm run test:prod
      - run: npm run lint

  deploy:
    runs-on: ubuntu-latest
    name: build&deploy
    steps:
      - name: SFTP uploader
        uses: wangyucode/sftp-upload-action@v2.0.2
        with:
          server: ${{ secrets.HOST }}
          username: ${{ secrets.USER }}
          password: ${{ secrets.PASSWORD }}
          localDir: "./build/*"
          remoteDir: "/var/www/industrial-holding"
