name: Continuous Deploy 

on:
  push:
    branches: ["main", "dev/*"]
  pull_request:
    branches: ["main", "dev/*"]

jobs:
  deploy-job:
    runs-on: ubuntu-latest
    name: build&deploy
    steps:
      - name: SFTP uploader
        uses: wangyucode/sftp-upload-action@v2.0.2
        with:
          server: '5.63.155.71'
          username: 'root'
          ssh_private_key: ${{ secrets.SSH_PRIVATE_KEY }}
          localDir: './build/*'
          remoteDir: '/var/www/industrial-holding'
